fix base path

diff --git a/.github/workflows/projects-dashboard.yml b/.github/workflows/projects-dashboard.yml
--- a/.github/workflows/projects-dashboard.yml
+++ b/.github/workflows/projects-dashboard.yml
@@ -13,18 +13,57 @@ on:
       - ".github/workflows/projects-dashboard.yml"
   workflow_dispatch:
 
-# Allow this job to clone the repo and create a page deployment
+# Allow this job to clone the repo and write comments
 permissions:
   contents: write
-  # pages: write
-  # id-token: write
+  pull-requests: write
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    outputs:
+      path: ${{ steps.get-target-folder.outputs.path }}
     steps:
       - name: Checkout your repository using git
         uses: actions/checkout@v4
+
+      - name: Get target folder
+        id: get-target-folder
+        env:
+          GITHUB_HEAD_REF: ${{ github.head_ref }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
+        run: |
+          echo "Current PATH: $PATH"
+          echo "Current shell: $SHELL"
+          which sed || echo "sed not found"
+          which tr || echo "tr not found"
+          ls /usr/bin
+
+          if [ "$GITHUB_HEAD_REF" != "" ]; then
+            # This is a pull request
+            BRANCH=$GITHUB_HEAD_REF
+          else
+            # This is a push to a branch
+            BRANCH=$GITHUB_REF_NAME
+          fi
+
+          TARGET_PATH=projects-dashboard
+          if [ "$BRANCH" != "main" ]; then
+            # sanitize branch name
+            BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9]/_/g')
+            TARGET_PATH=projects-dashboard-preview-$BRANCH
+          fi
+          echo "path=$TARGET_PATH" >> $GITHUB_OUTPUT
+
+          # replace basepath in astro.config.mjs using $PATH
+          sed -i "s|ospo/projects-dashboard|ospo/${TARGET_PATH}|g" projects-dashboard/astro.config.mjs
+          cat projects-dashboard/astro.config.mjs
+
+      - name: Prepare preview path
+        if: github.event_name == 'pull_request'
+        run: |
+          npm install -g pnpm
+
       - name: Install, build, and upload your site
         uses: withastro/action@v3
         with:
@@ -35,9 +74,6 @@ jobs:
   deploy:
     needs: build
     runs-on: ubuntu-latest
-    # environment:
-    #   name: github-pages
-    #   url: ${{ steps.deployment.outputs.page_url }}
     steps:
       - name: Checkout your repository using git
         uses: actions/checkout@v4
@@ -48,34 +84,13 @@ jobs:
           name: github-pages
           path: projects-dashboard-site
 
-      - name: Get target folder
-        id: get-target-folder
-        env:
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF_NAME: ${{ github.ref_name }}
+      - name: Unzip site artifact
         run: |
-          ls -R ./projects-dashboard-site
           cd ./projects-dashboard-site
           tar -xvf artifact.tar .
           rm artifact.tar
           cd ..
           ls -R ./projects-dashboard-site
-
-          if [ "$GITHUB_HEAD_REF" != "" ]; then
-            # This is a pull request
-            BRANCH=$GITHUB_HEAD_REF
-          else
-            # This is a push to a branch
-            BRANCH=$GITHUB_REF_NAME
-          fi
-
-          if [ "$BRANCH" != "main" ]; then
-            # sanitize branch name
-            BRANCH=$(echo "$BRANCH" | tr '/' '_')
-            echo "path=projects-dashboard-preview-$BRANCH" >> $GITHUB_OUTPUT
-          else
-            echo "path=projects-dashboard" >> $GITHUB_OUTPUT
-          fi
 
       - name: Deploy to GitHub Pages
         id: deployment
@@ -83,4 +98,13 @@ jobs:
         with:
           branch: gh-pages
           folder: projects-dashboard-site
-          target-folder: ${{ steps.get-target-folder.outputs.path }}
+          target-folder: ${{ needs.build.outputs.path }}
+
+      # Add a comment to the PR with the link to the deployed site
+      - name: Add preview comment to PR
+        if: github.event_name == 'pull_request'
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          message: |
+            Site preview deployed to: https://block-open-source.github.io/ospo/${{ needs.build.outputs.path }}
+          comment_tag: preview-deploy
